### ISSUE TITLE
Version 1.1.0 : Command not found

### ISSUE THREAD

**Issue by rfontess** [gsoft-inc/azure-devops-npm-auth#30] opened 2022-02-21 20:00 UTC
After update the command `npx azure-devops-npm-auth --client_id='xxxxxxx' --tenant_id='xxxxxxxxx'` is not working.

Version Npm: 8.5.1

**Error Console:**

sh: azure-devops-npm-auth: command not found
error Command failed with exit code 127.

Version **1.0.13** using the same command works normally.

**Comment by rooque** [comment] 2022-02-21 22:26
Same here...

Workaround:

```sh
npx azure-devops-npm-auth@1.0.13 --client_id='xxxxxxx' --tenant_id='xxxxxxxxx'
```

**Comment by ColinKrist** [comment] 2022-02-22 14:11
Are you guys running a specific OS? This is running fine for me in Windows, but my CI is Ubuntu and that's where I start to see failures.

![image](https://user-images.githubusercontent.com/27971797/155147989-8fc94fa3-b402-4878-b912-18bdbed0475f.png)

![image](https://user-images.githubusercontent.com/27971797/155148017-fc230828-4812-4669-b42b-8ac74f3cff0f.png)

**Comment by rfontess** [comment] 2022-02-22 15:55
> Are you guys running a specific OS? This is running fine for me in Windows, but my CI is Ubuntu and that's where I start to see failures.

I use macOs 10.15.7!

it's only working using the previous version `npx azure-devops-npm-auth@1.0.13 --client_id='xxxxxxx' --tenant_id='xxxxxxxxx'`

**Comment by Ranger1230** [comment] 2022-02-22 20:20
I'm on Windows 10 Pro Build 19044.1526 and I'm having the same issue. Using 1.0.13 fixes the issue so it's something in the new version.

**Comment by rooque** [comment] 2022-02-22 21:26
> Are you guys running a specific OS? This is running fine for me in Windows, but my CI is Ubuntu and that's where I start to see failures.

I'm on macOS 11.6.3, node v16.14.0.

**Comment by christianacca** [comment] 2022-02-24 08:02
I can confirm its an issue also when using yarn (v1.22.15) as your project's package manager. 

Pinning the version like @rfontess  explained (`npx azure-devops-npm-auth@1.0.13  --client_id='xxxxxxx' --tenant_id='xxxxxxxxx'`), works for me

**Comment by EbenZhang** [comment] 2022-03-08 07:46
Not exactly the same error message when running it on AzureDevOps with either Windows-Latest and Ubuntu-Latest image. But I believe it's the same issue.

Command used was `npm i -g azure-devops-npm-auth` in my pre-install. (I tried `npm i -g azure-devops-npm-auth@1.0.13`, it worked as someone mentioned in above comments)

The error message I got was: 

```
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /opt/hostedtoolcache/node/14.19.0/x64/lib/node_modules/azure-devops-npm-auth/dist/cli.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/opt/hostedtoolcache/node/14.19.0/x64/lib/node_modules/azure-devops-npm-auth/dist/cli.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```

**Comment by mike-dvorscak-enablon** [comment] 2022-03-14 15:26
I have the same issue mentioned by by @EbenZhang, when I look at the node_modules directory it looks like the `dist` directory wasn't published:
![image](https://user-images.githubusercontent.com/57106451/158204508-3b29ea99-b0ef-4e09-b89c-ad6df0808aa6.png)

@yohanb was there an issue during the latest publish (v 1.1.0) ?

**Comment by yohanb** [comment] 2022-03-14 16:01
hey everyone;  sorry for the late reply.  I'll have a look today.

**Comment by yohanb** [comment] 2022-03-14 17:29
I think I just derped with the 1.1.0 release 😬
v1.1.1, should fix the problem.  Someone please let me know so I can close the issue.

**Comment by mike-dvorscak-enablon** [comment] 2022-03-14 17:36
Latest version (1.1.1) seems to be good (at least containing the dist folder)

**Closed** 2022-03-14 17:39 UTC
